In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("Covid-19 Dataset.csv")

In [3]:
df.head()

        Date State       Region  Confirmed  Deaths  Recovered
0  4/29/2020   NaN  Afghanistan       1939      60        252
1  4/29/2020   NaN      Albania        766      30        455
2  4/29/2020   NaN      Algeria       3848     444       1702
3  4/29/2020   NaN      Andorra        743      42        423
4  4/29/2020   NaN       Angola         27       2          7

In [4]:
# Q.4-1) Show the number of Confirmed, Deaths and Recovered cases in each Region.
df.groupby('Region')[['Confirmed', 'Deaths', 'Recovered']].sum()

                    Confirmed  Deaths  Recovered
Region
Afghanistan              1939      60        252
Albania                   766      30        455
Algeria                  3848     444       1702
Andorra                   743      42        423
Angola                     27       2          7
...                       ...     ...        ...
West Bank and Gaza        344       2         71
Western Sahara              6       0          5
Yemen                       6       0          1
Zambia                     97       3         54
Zimbabwe                   32       4          5

[187 rows x 3 columns]

In [5]:
# Q.4-2) Remove all the records where the Confirmed Cases is Less Than 10.
df = df[df['Confirmed'] >= 10]
df

          Date     State          Region  Confirmed  Deaths  Recovered
0    4/29/2020       NaN     Afghanistan       1939      60        252
1    4/29/2020       NaN         Albania        766      30        455
2    4/29/2020       NaN         Algeria       3848     444       1702
3    4/29/2020       NaN         Andorra        743      42        423
4    4/29/2020       NaN          Angola         27       2          7
..         ...       ...             ...        ...     ...        ...
316  4/29/2020   Wyoming              US        545       7          0
317  4/29/2020  Xinjiang  Mainland China         76       3         73
318  4/29/2020     Yukon          Canada         11       0          0
319  4/29/2020    Yunnan  Mainland China        185       2        181
320  4/29/2020  Zhejiang  Mainland China       1268       1       1263

[304 rows x 6 columns]

In [6]:
# Q.4-3) In which Region, maximum number of Confirmed cases were recorded ?
df.groupby('Region')['Confirmed'].sum().sort_values(ascending=False).head(1)

Region
US    1039909
Name: Confirmed, dtype: int64

In [7]:
# Q.4-4) In which Region, minimum number of Deaths cases were recorded ?
df.groupby('Region')['Deaths'].sum().sort_values(ascending=True)

Region
Cambodia                        0
Fiji                            0
Dominica                        0
Central African Republic        0
Eritrea                         0
                            ...
France                      24121
Spain                       24275
UK                          26165
Italy                       27682
US                          60967
Name: Deaths, Length: 180, dtype: int64

In [8]:
# Q.4-5) How many Confirmed, Deaths & Recovered cases were reported from India till 29 April 2020 ?
df[df['Region'] == 'India']

         Date State Region  Confirmed  Deaths  Recovered
74  4/29/2020   NaN  India      33062    1079       8437

In [9]:
# Q.4-6-A ) Sort the entire data wrt No. of Confirmed cases in ascending order.
df.sort_values(by=['Confirmed'], ascending=True)

          Date      State    Region  Confirmed  Deaths  Recovered
70   4/29/2020        NaN  Holy See         10       0          2
59   4/29/2020        NaN    Gambia         10       1          8
156  4/29/2020        NaN  Suriname         10       1          8
27   4/29/2020        NaN   Burundi         11       1          4
217  4/29/2020  Greenland   Denmark         11       0         11
..         ...        ...       ...        ...     ...        ...
57   4/29/2020        NaN    France     165093   24087      48228
168  4/29/2020        NaN        UK     165221   26097          0
80   4/29/2020        NaN     Italy     203591   27682      71252
153  4/29/2020        NaN     Spain     236899   24275     132929
265  4/29/2020   New York        US     299691   23477          0

[304 rows x 6 columns]

In [10]:
# Q.4-6-B ) Sort the entire data wrt No. of Recovered cases in descending order.
df.sort_values(by=['Recovered'], ascending=False)

,Date,State,Region,Confirmed,Deaths,Recovered
153,4/29/2020,NaN,Spain,236899,24275,132929
61,4/29/2020,NaN,Germany,161539,6467,120400
76,4/29/2020,NaN,Iran,93657,5957,73791
80,4/29/2020,NaN,Italy,203591,27682,71252
229,4/29/2020,Hubei,Mainland China,68128,4512,63616
...,...,...,...,...,...,...
270,4/29/2020,Northern Mariana Islands,US,14,2,0
299,4/29/2020,South Dakota,US,2373,13,0
298,4/29/2020,South Carolina,US,5882,231,0
302,4/29/2020,Tennessee,US,10366,195,0
303,4/29/2020,Texas,US,27257,754,0